package com.sreepadmavathi.saree.service;

import com.sreepadmavathi.saree.entity.Customer;
import com.sreepadmavathi.saree.repository.CustomerRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;

@Service
public class CustomerService {

    private final CustomerRepository customerRepository;
    public CustomerService(CustomerRepository customerRepository) {
        this.customerRepository = customerRepository;
    }

    @Transactional
    public Customer resolveCustomer(String phone, String name, String address) {
        return resolveCustomer(phone, name, address, null);
    }

    @Transactional
    public Customer resolveCustomer(String phone, String name, String address, String email) {
        Optional<Customer> existingCustomer = customerRepository.findByPhone(phone);

        if (existingCustomer.isPresent()) {
            Customer customer = existingCustomer.get();
            boolean updated = false;

            if (name != null && !name.equals(customer.getCustomerName())) {
                customer.setCustomerName(name);
                updated = true;
            }
            if (address != null && !address.equals(customer.getAddress())) {
                customer.setAddress(address);
                updated = true;
            }
            if (email != null && !email.isBlank() && !email.equals(customer.getEmail())) {
                customer.setEmail(email);
                updated = true;
            }

            if (updated) {
                return customerRepository.save(customer);
            }
            return customer;
        }

        try {
            return createNewCustomer(phone, name, address, email);
        } catch (DataIntegrityViolationException e) {
            // Race condition: another thread created the customer with this phone just now
            return customerRepository.findByPhone(phone)
                    .orElseThrow(() -> new RuntimeException("Failed to find customer after constraint violation"));
        }
    }

    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public Customer createNewCustomer(String phone, String name, String address, String email) {
        Customer newCustomer = new Customer();
        newCustomer.setPhone(phone);
        newCustomer.setCustomerName(name);
        newCustomer.setAddress(address);
        newCustomer.setEmail(email);
        // Note: customerCode will be auto-generated by the database trigger/default or we can generate it
        newCustomer.setCustomerCode("CUST-" + System.currentTimeMillis());

        return customerRepository.saveAndFlush(newCustomer);
    }
}
